In [10]:
from sodapy import Socrata
import pandas as pd

client = Socrata(
    "www.datos.gov.co",
    None
)

results = client.get(
    "jbjy-vk9h",
    limit=5
)

df = pd.DataFrame(results)

print(df.columns.tolist())

df.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

['nombre_entidad', 'nit_entidad', 'departamento', 'ciudad', 'localizaci_n', 'orden', 'sector', 'rama', 'entidad_centralizada', 'proceso_de_compra', 'id_contrato', 'referencia_del_contrato', 'estado_contrato', 'codigo_de_categoria_principal', 'descripcion_del_proceso', 'tipo_de_contrato', 'modalidad_de_contratacion', 'justificacion_modalidad_de', 'fecha_de_firma', 'fecha_de_inicio_del_contrato', 'fecha_de_fin_del_contrato', 'condiciones_de_entrega', 'tipodocproveedor', 'documento_proveedor', 'proveedor_adjudicado', 'es_grupo', 'es_pyme', 'habilita_pago_adelantado', 'liquidaci_n', 'obligaci_n_ambiental', 'obligaciones_postconsumo', 'reversion', 'origen_de_los_recursos', 'destino_gasto', 'valor_del_contrato', 'valor_de_pago_adelantado', 'valor_facturado', 'valor_pendiente_de_pago', 'valor_pagado', 'valor_amortizado', 'valor_pendiente_de', 'valor_pendiente_de_ejecucion', 'saldo_cdp', 'saldo_vigencia', 'espostconflicto', 'dias_adicionados', 'puntos_del_acuerdo', 'pilares_del_acuerdo', 'urlproceso', 'nombre_representante_legal', 'nacionalidad_representante_legal', 'domicilio_representante_legal', 'tipo_de_identificaci_n_representante_legal', 'identificaci_n_representante_legal', 'g_nero_representante_legal', 'recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_', 'ultima_actualizacion', 'codigo_entidad', 'codigo_proveedor', 'fecha_inicio_liquidacion', 'fecha_fin_liquidacion', 'objeto_del_contrato', 'duraci_n_del_contrato', 'nombre_del_banco', 'tipo_de_cuenta', 'n_mero_de_cuenta', 'el_contrato_puede_ser_prorrogado', 'fecha_de_notificaci_n_de_prorrogaci_n', 'nombre_ordenador_del_gasto', 'tipo_de_documento_ordenador_del_gasto', 'n_mero_de_documento_ordenador_del_gasto', 'nombre_supervisor', 'tipo_de_documento_supervisor', 'n_mero_de_documento_supervisor', 'nombre_ordenador_de_pago', 'tipo_de_documento_ordenador_de_pago', 'n_mero_de_documento_ordenador_de_pago', 'documentos_tipo', 'descripcion_documentos_tipo']

,nombre_entidad,nit_entidad,departamento,ciudad,localizaci_n,orden,sector,rama,entidad_centralizada,proceso_de_compra,...,tipo_de_documento_ordenador_del_gasto,n_mero_de_documento_ordenador_del_gasto,nombre_supervisor,tipo_de_documento_supervisor,n_mero_de_documento_supervisor,nombre_ordenador_de_pago,tipo_de_documento_ordenador_de_pago,n_mero_de_documento_ordenador_de_pago,documentos_tipo,descripcion_documentos_tipo
0,PARQUES NACIONALES NATURALES DE COLOMBIA - DIR...,900005502,Distrito Capital de Bogotá,No Definido,"Colombia, Bogotá, No Definido",Territorial,Ambiente y Desarrollo Sostenible,Ejecutivo,Centralizada,CO1.BDOS.848814,...,Cédula de Ciudadanía,51698201,ARTEMIO CANO TABARES,Cédula de Ciudadanía,15888923,No definido,No definido,No definido,No,No definido
1,ESTABLECIMIENTO CARCELARIO PURIFICACION,809003243,No Definido,No Definido,"Colombia, No Definido, No Definido",Nacional,Ley de Justicia,Judicial,Centralizada,CO1.BDOS.855601,...,No definido,No definido,No definido,No definido,No definido,No definido,No definido,No definido,No,No definido
2,AGENCIA NACIONAL DE DEFENSA JURÍDICA DEL ESTADO,900507741,Distrito Capital de Bogotá,No Definido,"Colombia, Bogotá, No Definido",Nacional,Ley de Justicia,Ejecutivo,Descentralizada,CO1.BDOS.115112,...,No definido,No definido,No definido,No definido,No definido,No definido,No definido,No definido,No,No definido
3,AGENCIA NACIONAL DE DEFENSA JURÍDICA DEL ESTADO,900507741,Distrito Capital de Bogotá,No Definido,"Colombia, Bogotá, No Definido",Nacional,Ley de Justicia,Ejecutivo,Descentralizada,CO1.BDOS.115113,...,No definido,No definido,No definido,No definido,No definido,No definido,No definido,No definido,No,No definido
4,AGENCIA NACIONAL DE DEFENSA JURÍDICA DEL ESTADO,900507741,Distrito Capital de Bogotá,No Definido,"Colombia, Bogotá, No Definido",Nacional,Ley de Justicia,Ejecutivo,Descentralizada,CO1.BDOS.115022,...,No definido,No definido,No definido,No definido,No definido,No definido,No definido,No definido,No,No definido

In [12]:
#filtrar columa id del contrato

df_2 = df[["id_contrato"]]

df_2

          id_contrato
0  CO1.PCCNTR.1000001
1  CO1.PCCNTR.1000002
2   CO1.PCCNTR.100001
3   CO1.PCCNTR.100002
4   CO1.PCCNTR.100003

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 79 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   nombre_entidad                                                    5 non-null      str
 1   nit_entidad                                                       5 non-null      str
 2   departamento                                                      5 non-null      str
 3   ciudad                                                            5 non-null      str
 4   localizaci_n                                                      5 non-null      str
 5   orden                                                             5 non-null      str
 6   sector                                                            5 non-null      str
 7   rama                                                              5 non-null      str
 8   entidad_centralizada                                              5 non-null      str
 9   proceso_de_compra                                                 5 non-null      str
 10  id_contrato                                                       5 non-null      str
 11  referencia_del_contrato                                           5 non-null      str
 12  estado_contrato                                                   5 non-null      str
 13  codigo_de_categoria_principal                                     5 non-null      str
 14  descripcion_del_proceso                                           5 non-null      str
 15  tipo_de_contrato                                                  5 non-null      str
 16  modalidad_de_contratacion                                         5 non-null      str
 17  justificacion_modalidad_de                                        5 non-null      str
 18  fecha_de_firma                                                    4 non-null      str
 19  fecha_de_inicio_del_contrato                                      4 non-null      str
 20  fecha_de_fin_del_contrato                                         4 non-null      str
 21  condiciones_de_entrega                                            5 non-null      str
 22  tipodocproveedor                                                  5 non-null      str
 23  documento_proveedor                                               5 non-null      str
 24  proveedor_adjudicado                                              5 non-null      str
 25  es_grupo                                                          5 non-null      str
 26  es_pyme                                                           5 non-null      str
 27  habilita_pago_adelantado                                          5 non-null      str
 28  liquidaci_n                                                       5 non-null      str
 29  obligaci_n_ambiental                                              5 non-null      str
 30  obligaciones_postconsumo                                          5 non-null      str
 31  reversion                                                         5 non-null      str
 32  origen_de_los_recursos                                            5 non-null      str
 33  destino_gasto                                                     5 non-null      str
 34  valor_del_contrato                                                5 non-null      str
 35  valor_de_pago_adelantado                                          5 non-null      str
 36  valor_facturado                                                   5 non-null      str
 37  valor_pendiente_de_pago                                           5 non-null      str
 38  valor_pagado                                                      5 non-null      str
 39  valor_amortizado                                                  5 non-null      str
 40  valor_pendiente_de                                                5 non-null      str
 41  valor_pendiente_de_ejecucion                                      5 non-null      str
 42  saldo_cdp                                                         5 non-null      str
 43  saldo_vigencia                                                    5 non-null      str
 44  espostconflicto                                                   5 non-null      str
 45  dias_adicionados                                                  5 non-null      str
 46  puntos_del_acuerdo                                                5 non-null      str
 47  pilares_del_acuerdo                                               5 non-null      str
 48  urlproceso                                                        5 non-null      object
 49  nombre_representante_legal                                        5 non-null      str
 50  nacionalidad_representante_legal                                  5 non-null      str
 51  domicilio_representante_legal                                     5 non-null      str
 52  tipo_de_identificaci_n_representante_legal                        5 non-null      str
 53  identificaci_n_representante_legal                                5 non-null      str
 54  g_nero_representante_legal                                        5 non-null      str
 55  recursos_propios_alcald_as_gobernaciones_y_resguardos_ind_genas_  5 non-null      str
 56  ultima_actualizacion                                              4 non-null      str
 57  codigo_entidad                                                    5 non-null      str
 58  codigo_proveedor                                                  5 non-null      str
 59  fecha_inicio_liquidacion                                          1 non-null      str
 60  fecha_fin_liquidacion                                             1 non-null      str
 61  objeto_del_contrato                                               5 non-null      str
 62  duraci_n_del_contrato                                             5 non-null      str
 63  nombre_del_banco                                                  5 non-null      str
 64  tipo_de_cuenta                                                    5 non-null      str
 65  n_mero_de_cuenta                                                  5 non-null      str
 66  el_contrato_puede_ser_prorrogado                                  5 non-null      str
 67  fecha_de_notificaci_n_de_prorrogaci_n                             1 non-null      str
 68  nombre_ordenador_del_gasto                                        5 non-null      str
 69  tipo_de_documento_ordenador_del_gasto                             5 non-null      str
 70  n_mero_de_documento_ordenador_del_gasto                           5 non-null      str
 71  nombre_supervisor                                                 5 non-null      str
 72  tipo_de_documento_supervisor                                      5 non-null      str
 73  n_mero_de_documento_supervisor                                    5 non-null      str
 74  nombre_ordenador_de_pago                                          5 non-null      str
 75  tipo_de_documento_ordenador_de_pago                               5 non-null      str
 76  n_mero_de_documento_ordenador_de_pago                             5 non-null      str
 77  documentos_tipo                                                   5 non-null      str
 78  descripcion_documentos_tipo                                       5 non-null      str
dtypes: object(1), str(78)
memory usage: 3.2+ KB